// Cross-language protocol type assertion test
// Reads fixture JSON generated by Python and validates each message
// against the TypeScript type definitions.

import { describe, it, expect } from "vitest";
import fixtures from "./protocol-fixtures.json";
import type {
  Hello,
  OpenWorkspace,
  UserMessage,
  Approve,
  Deny,
  Resume,
  Cancel,
  Attach,
  Detach,
  SetTier,
  GetInstructionStack,
  Ready,
  SessionState,
  AssistantDelta,
  BoundaryUpdate,
  ToolCall,
  ToolResult,
  ApprovalRequest,
  DecisionLogged,
  CheckpointNotice,
  CostUpdate,
  TurnComplete,
  Error,
} from "./protocol";

// ── Helpers ───────────────────────────────────────────────────────────

function hasKeys(obj: unknown, keys: string[]): boolean {
  if (typeof obj !== "object" || obj === null) return false;
  return keys.every((k) => k in obj);
}

function isString(v: unknown): v is string {
  return typeof v === "string";
}

function isNumber(v: unknown): v is number {
  return typeof v === "number" && !isNaN(v);
}

function isBoolean(v: unknown): v is boolean {
  return typeof v === "boolean";
}

// ── Client messages ───────────────────────────────────────────────────

describe("Client message fixtures match TypeScript types", () => {
  it("hello", () => {
    const m = fixtures.hello as Hello;
    expect(m.type).toBe("hello");
    expect(isString(m.token)).toBe(true);
    expect(isNumber(m.version)).toBe(true);
  });

  it("open_workspace", () => {
    const m = fixtures.open_workspace as OpenWorkspace;
    expect(m.type).toBe("open_workspace");
    expect(isString(m.path)).toBe(true);
  });

  it("user_message", () => {
    const m = fixtures.user_message as UserMessage;
    expect(m.type).toBe("user_message");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.content)).toBe(true);
  });

  it("approve", () => {
    const m = fixtures.approve as Approve;
    expect(m.type).toBe("approve");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.tool_call_id)).toBe(true);
  });

  it("deny", () => {
    const m = fixtures.deny as Deny;
    expect(m.type).toBe("deny");
    expect(isString(m.reason)).toBe(true);
    // deny_no_reason has null reason
    const m2 = fixtures.deny_no_reason as Deny;
    expect(m2.reason).toBeNull();
  });

  it("cancel", () => {
    const m = fixtures.cancel as Cancel;
    expect(m.type).toBe("cancel");
    expect(isString(m.session_id)).toBe(true);
  });

  it("attach", () => {
    const m = fixtures.attach as Attach;
    expect(m.type).toBe("attach");
    expect(isNumber(m.from_seq)).toBe(true);
  });

  it("detach", () => {
    const m = fixtures.detach as Detach;
    expect(m.type).toBe("detach");
    expect(isString(m.session_id)).toBe(true);
  });

  it("set_tier", () => {
    const m = fixtures.set_tier as SetTier;
    expect(m.type).toBe("set_tier");
    expect(m.tier).toBe("brain");
  });

  it("get_instruction_stack", () => {
    const m = fixtures.get_instruction_stack as GetInstructionStack;
    expect(m.type).toBe("get_instruction_stack");
    expect(isString(m.session_id)).toBe(true);
  });
});

// ── Daemon events ─────────────────────────────────────────────────────

describe("Daemon event fixtures match TypeScript types", () => {
  it("ready", () => {
    const m = fixtures.ready as Ready;
    expect(m.type).toBe("ready");
    expect(isString(m.version)).toBe(true);
    expect(isNumber(m.protocol_version)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("session_state", () => {
    const m = fixtures.session_state as SessionState;
    expect(m.type).toBe("session_state");
    expect(m.state).toBe("running");
    expect(isNumber(m.seq)).toBe(true);
  });

  it("session_state_paused", () => {
    const m = fixtures.session_state_paused as SessionState;
    expect(m.type).toBe("session_state");
    expect(m.state).toBe("paused");
    expect(isString(m.reason)).toBe(true);
  });

  it("resume", () => {
    const m = fixtures.resume as Resume;
    expect(m.type).toBe("resume");
    expect(isString(m.session_id)).toBe(true);
  });

  it("assistant_delta", () => {
    const m = fixtures.assistant_delta as AssistantDelta;
    expect(m.type).toBe("assistant_delta");
    expect(isString(m.delta)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("tool_call", () => {
    const m = fixtures.tool_call as ToolCall;
    expect(m.type).toBe("tool_call");
    expect(isString(m.tool_call_id)).toBe(true);
    expect(isString(m.name)).toBe(true);
    expect(typeof m.arguments).toBe("object");
    expect(m.decision_class).toBe("B");
    expect(isNumber(m.seq)).toBe(true);
  });

  it("tool_result", () => {
    const m = fixtures.tool_result as ToolResult;
    expect(m.type).toBe("tool_result");
    expect(m.status).toBe("success");
    expect(isString(m.output)).toBe(true);
    expect(isBoolean(m.truncated)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
    // truncated variant
    const m2 = fixtures.tool_result_truncated as ToolResult;
    expect(m2.truncated).toBe(true);
    expect(m2.status).toBe("error");
    // write variant carries the diff for display (TD-604)
    const m3 = fixtures.tool_result_diff as ToolResult;
    expect(isString(m3.diff)).toBe(true);
    expect(m3.diff).toContain("--- a/test.txt");
  });

  it("approval_request", () => {
    const m = fixtures.approval_request as ApprovalRequest;
    expect(m.type).toBe("approval_request");
    expect(isString(m.tool_name)).toBe(true);
    expect(m.decision_class).toBe("C");
    expect(isString(m.summary)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("decision_logged", () => {
    const m = fixtures.decision_logged as DecisionLogged;
    expect(m.type).toBe("decision_logged");
    expect(m.decision_class).toBe("A");
    expect(isString(m.what)).toBe(true);
    expect(isString(m.why)).toBe(true);
    expect(isString(m.commit)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("checkpoint_notice", () => {
    const m = fixtures.checkpoint_notice as CheckpointNotice;
    expect(m.type).toBe("checkpoint_notice");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.code)).toBe(true);
    expect(isString(m.message)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("cost_update", () => {
    const m = fixtures.cost_update as CostUpdate;
    expect(m.type).toBe("cost_update");
    expect(isNumber(m.turn_cost)).toBe(true);
    expect(isNumber(m.session_cost)).toBe(true);
    expect(isNumber(m.total_cost)).toBe(true);
    expect(isNumber(m.classifier_cost)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("boundary_update", () => {
    const m = fixtures.boundary_update as BoundaryUpdate;
    expect(m.type).toBe("boundary_update");
    expect(Array.isArray(m.writable_paths)).toBe(true);
    expect(Array.isArray(m.allowed_commands)).toBe(true);
    expect(isString(m.network) || Array.isArray(m.network)).toBe(true);
    expect(isNumber(m.spend_usd)).toBe(true);
    expect(isNumber(m.wall_clock_hours)).toBe(true);
    expect(isNumber(m.max_iterations)).toBe(true);
    expect(isString(m.source)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("turn_complete", () => {
    const m = fixtures.turn_complete as TurnComplete;
    expect(m.type).toBe("turn_complete");
    expect(isNumber(m.tokens)).toBe(true);
    expect(isNumber(m.cost)).toBe(true);
    expect(m.tier).toBe("worker");
    expect(isNumber(m.duration)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("error", () => {
    const m = fixtures.error as Error;
    expect(m.type).toBe("error");
    expect(isString(m.code)).toBe(true);
    expect(isString(m.message)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
    // error_with_session has session_id
    const m2 = fixtures.error_with_session as Error;
    expect(isString(m2.session_id)).toBe(true);
  });
});

// ── Structural checks ─────────────────────────────────────────────────

describe("All fixtures have required shape", () => {
  it("every client message has a type field", () => {
    const clientTypes = [
      "hello", "open_workspace", "user_message", "approve", "deny",
      "deny_no_reason", "cancel", "attach", "detach", "set_tier",
      "get_instruction_stack",
    ];
    for (const key of clientTypes) {
      const msg = (fixtures as Record<string, unknown>)[key] as Record<string, unknown>;
      expect(typeof msg.type).toBe("string");
    }
  });

  it("every daemon event has a type and seq field", () => {
    const eventTypes = [
      "ready", "session_state", "assistant_delta", "tool_call", "tool_result",
      "tool_result_truncated", "tool_result_diff", "approval_request",
      "decision_logged", "checkpoint_notice", "cost_update", "turn_complete",
      "error", "error_with_session",
    ];
    for (const key of eventTypes) {
      const evt = (fixtures as Record<string, unknown>)[key] as Record<string, unknown>;
      expect(typeof evt.type).toBe("string");
      expect(typeof evt.seq).toBe("number");
    }
  });
});