// Cross-language protocol type assertion test
// Reads fixture JSON generated by Python and validates each message
// against the TypeScript type definitions.

import { describe, it, expect } from "vitest";
import fixtures from "./protocol-fixtures.json";
import type {
  Hello,
  HelloAck,
  OpenWorkspace,
  UserMessage,
  ForkFrom,
  SetBranch,
  ConversationReset,
  Approve,
  Deny,
  AlwaysAllow,
  ListPolicyRules,
  RevokePolicyRule,
  Resume,
  Cancel,
  Attach,
  Detach,
  SetTier,
  GetInstructionStack,
  ListInstructions,
  CreateRule,
  EndSession,
  InstructionFiles,
  MemoryAccept,
  MemoryEdit,
  MemoryProposal,
  MemoryReject,
  Shutdown,
  ListSessions,
  Ready,
  SessionState,
  AssistantDelta,
  AssistantReasoning,
  UserTurn,
  BoundaryUpdate,
  ToolCall,
  ToolResult,
  ShellOutput,
  ApprovalRequest,
  DecisionLogged,
  CheckpointNotice,
  CostUpdate,
  TierState,
  TurnComplete,
  ContextCompacted,
  SteeringReloaded,
  RuleActivated,
  TierSwitched,
  InstructionStack,
  SessionList,
  SessionSummary,
  ArchiveSession,
  DeleteSession,
  MoveSession,
  PolicyRules,
  PolicyRuleSummary,
  GetSetupState,
  SetApiKey,
  ValidateApiKey,
  SetPreset,
  SetSkipAllApprovals,
  SetupState,
  ApiKeyValidated,
  RunDiagnostics,
  DiagnosticsReport,
  GetUsage,
  ExportUsage,
  UsageReport,
  UsageExported,
  Ping,
  Error,
  Attachment,
} from "./protocol";

// ── Helpers ───────────────────────────────────────────────────────────

function hasKeys(obj: unknown, keys: string[]): boolean {
  if (typeof obj !== "object" || obj === null) return false;
  return keys.every((k) => k in obj);
}

function isString(v: unknown): v is string {
  return typeof v === "string";
}

function isNumber(v: unknown): v is number {
  return typeof v === "number" && !isNaN(v);
}

function isBoolean(v: unknown): v is boolean {
  return typeof v === "boolean";
}

// ── Client messages ───────────────────────────────────────────────────

describe("Client message fixtures match TypeScript types", () => {
  it("hello", () => {
    const m = fixtures.hello as Hello;
    expect(m.type).toBe("hello");
    expect(isString(m.token)).toBe(true);
    expect(isNumber(m.version)).toBe(true);
  });

  it("open_workspace", () => {
    const m = fixtures.open_workspace as OpenWorkspace;
    expect(m.type).toBe("open_workspace");
    expect(isString(m.path)).toBe(true);
  });

  it("fork_from", () => {
    const m = fixtures.fork_from as ForkFrom;
    expect(m.type).toBe("fork_from");
    expect(isNumber(m.user_index)).toBe(true);
    expect(isString(m.content)).toBe(true);
  });

  it("set_branch", () => {
    const m = fixtures.set_branch as SetBranch;
    expect(m.type).toBe("set_branch");
    expect(isNumber(m.sibling_index)).toBe(true);
  });

  it("user_message", () => {
    const m = fixtures.user_message as UserMessage;
    expect(m.type).toBe("user_message");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.content)).toBe(true);
  });

  it("approve", () => {
    const m = fixtures.approve as Approve;
    expect(m.type).toBe("approve");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.tool_call_id)).toBe(true);
  });

  it("deny", () => {
    const m = fixtures.deny as Deny;
    expect(m.type).toBe("deny");
    expect(isString(m.reason)).toBe(true);
    // deny_no_reason has null reason
    const m2 = fixtures.deny_no_reason as Deny;
    expect(m2.reason).toBeNull();
  });

  it("always_allow", () => {
    const m = fixtures.always_allow as AlwaysAllow;
    expect(m.type).toBe("always_allow");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.tool_call_id)).toBe(true);
  });

  it("list_policy_rules", () => {
    const m = fixtures.list_policy_rules as ListPolicyRules;
    expect(m.type).toBe("list_policy_rules");
    expect(isString(m.session_id)).toBe(true);
  });

  it("set_skip_all_approvals", () => {
    const m = fixtures.set_skip_all_approvals as SetSkipAllApprovals;
    expect(m.type).toBe("set_skip_all_approvals");
    expect(isBoolean(m.enabled)).toBe(true);
    expect("session_id" in m).toBe(false);
  });

  it("revoke_policy_rule", () => {
    const m = fixtures.revoke_policy_rule as RevokePolicyRule;
    expect(m.type).toBe("revoke_policy_rule");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.tool)).toBe(true);
    expect(isString(m.args)).toBe(true);
  });

  it("cancel", () => {
    const m = fixtures.cancel as Cancel;
    expect(m.type).toBe("cancel");
    expect(isString(m.session_id)).toBe(true);
  });

  it("attach", () => {
    const m = fixtures.attach as Attach;
    expect(m.type).toBe("attach");
    expect(isNumber(m.from_seq)).toBe(true);
  });

  it("detach", () => {
    const m = fixtures.detach as Detach;
    expect(m.type).toBe("detach");
    expect(isString(m.session_id)).toBe(true);
  });

  it("set_tier", () => {
    const m = fixtures.set_tier as SetTier;
    expect(m.type).toBe("set_tier");
    expect(m.tier).toBe("brain");
  });

  it("get_instruction_stack", () => {
    const m = fixtures.get_instruction_stack as GetInstructionStack;
    expect(m.type).toBe("get_instruction_stack");
    expect(isString(m.session_id)).toBe(true);
  });

  it("list_instructions", () => {
    const m = fixtures.list_instructions as ListInstructions;
    expect(m.type).toBe("list_instructions");
    expect(isString(m.workspace_path)).toBe(true);
  });

  it("create_rule", () => {
    const m = fixtures.create_rule as CreateRule;
    expect(m.type).toBe("create_rule");
    expect(isString(m.name)).toBe(true);
  });

  it("memory_accept", () => {
    const m = fixtures.memory_accept as MemoryAccept;
    expect(m.type).toBe("memory_accept");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.proposal_id)).toBe(true);
  });

  it("memory_edit", () => {
    const m = fixtures.memory_edit as MemoryEdit;
    expect(m.type).toBe("memory_edit");
    expect(isString(m.proposal_id)).toBe(true);
    expect(Array.isArray(m.files)).toBe(true);
  });

  it("memory_reject", () => {
    const m = fixtures.memory_reject as MemoryReject;
    expect(m.type).toBe("memory_reject");
    expect(isString(m.proposal_id)).toBe(true);
  });

  it("end_session", () => {
    const m = fixtures.end_session as EndSession;
    expect(m.type).toBe("end_session");
    expect(isString(m.session_id)).toBe(true);
  });

  it("shutdown", () => {
    const m = fixtures.shutdown as Shutdown;
    expect(m.type).toBe("shutdown");
  });

  it("list_sessions", () => {
    const m = fixtures.list_sessions as ListSessions;
    expect(m.type).toBe("list_sessions");
  });

  // TD-1101 first-run wizard
  it("get_setup_state", () => {
    const m = fixtures.get_setup_state as GetSetupState;
    expect(m.type).toBe("get_setup_state");
  });

  it("set_api_key", () => {
    const m = fixtures.set_api_key as SetApiKey;
    expect(m.type).toBe("set_api_key");
    expect(isString(m.api_key)).toBe(true);
  });

  it("validate_api_key", () => {
    const m = fixtures.validate_api_key as ValidateApiKey;
    expect(m.type).toBe("validate_api_key");
  });

  it("set_preset", () => {
    const m = fixtures.set_preset as SetPreset;
    expect(m.type).toBe("set_preset");
    expect(isString(m.name)).toBe(true);
  });

  // TD-1104 doctor
  it("run_diagnostics", () => {
    const m = fixtures.run_diagnostics as RunDiagnostics;
    expect(m.type).toBe("run_diagnostics");
  });

  // TD-1706 usage view
  it("get_usage", () => {
    const m = fixtures.get_usage as GetUsage;
    expect(m.type).toBe("get_usage");
    // Connection-scoped: the audit store spans every session.
    expect("session_id" in m).toBe(false);
  });

  it("export_usage", () => {
    const m = fixtures.export_usage as ExportUsage;
    expect(m.type).toBe("export_usage");
    expect(["jsonl", "csv"]).toContain(m.format);
    // Format only — no client-supplied destination path.
    expect("path" in m).toBe(false);
  });

  // hello_ack is out-of-band and unsequenced: daemon→client, no seq.
  it("hello_ack", () => {
    const m = fixtures.hello_ack as HelloAck;
    expect(m.type).toBe("hello_ack");
    expect(isNumber(m.version)).toBe(true);
  });
});

// ── Daemon events ─────────────────────────────────────────────────────

describe("Daemon event fixtures match TypeScript types", () => {
  it("ready", () => {
    const m = fixtures.ready as Ready;
    expect(m.type).toBe("ready");
    expect(isString(m.version)).toBe(true);
    expect(isNumber(m.protocol_version)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("session_state", () => {
    const m = fixtures.session_state as SessionState;
    expect(m.type).toBe("session_state");
    expect(m.state).toBe("running");
    expect(isNumber(m.seq)).toBe(true);
  });

  it("session_state_paused", () => {
    const m = fixtures.session_state_paused as SessionState;
    expect(m.type).toBe("session_state");
    expect(m.state).toBe("paused");
    expect(isString(m.reason)).toBe(true);
  });

  it("resume", () => {
    const m = fixtures.resume as Resume;
    expect(m.type).toBe("resume");
    expect(isString(m.session_id)).toBe(true);
  });

  it("user_turn", () => {
    const m = fixtures.user_turn as UserTurn;
    expect(m.type).toBe("user_turn");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.turn_id)).toBe(true);
    expect(isString(m.content)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("assistant_delta", () => {
    const m = fixtures.assistant_delta as AssistantDelta;
    expect(m.type).toBe("assistant_delta");
    expect(isString(m.delta)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("assistant_reasoning", () => {
    const m = fixtures.assistant_reasoning as AssistantReasoning;
    expect(m.type).toBe("assistant_reasoning");
    expect(isString(m.delta)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("tool_call", () => {
    const m = fixtures.tool_call as ToolCall;
    expect(m.type).toBe("tool_call");
    expect(isString(m.tool_call_id)).toBe(true);
    expect(isString(m.name)).toBe(true);
    expect(typeof m.arguments).toBe("object");
    expect(m.decision_class).toBe("B");
    expect(isNumber(m.seq)).toBe(true);
  });

  it("tool_result", () => {
    const m = fixtures.tool_result as ToolResult;
    expect(m.type).toBe("tool_result");
    expect(m.status).toBe("success");
    expect(isString(m.output)).toBe(true);
    expect(isBoolean(m.truncated)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
    // truncated variant
    const m2 = fixtures.tool_result_truncated as ToolResult;
    expect(m2.truncated).toBe(true);
    expect(m2.status).toBe("error");
    // write variant carries the diff for display (TD-604)
    const m3 = fixtures.tool_result_diff as ToolResult;
    expect(isString(m3.diff)).toBe(true);
    expect(m3.diff).toContain("--- a/test.txt");
    // denial variant carries the machine-readable error_code (TD-1007)
    const m4 = fixtures.tool_result_denied as ToolResult;
    expect(m4.status).toBe("error");
    expect(m4.error_code).toBe("approval_denied");
  });

  it("shell_output", () => {
    const m = fixtures.shell_output as ShellOutput;
    expect(m.type).toBe("shell_output");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.tool_call_id)).toBe(true);
    expect(m.stream).toBe("stdout");
    expect(isString(m.chunk)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("approval_request", () => {
    const m = fixtures.approval_request as ApprovalRequest;
    expect(m.type).toBe("approval_request");
    expect(isString(m.tool_name)).toBe(true);
    expect(m.decision_class).toBe("C");
    expect(isString(m.summary)).toBe(true);
    expect(isString(m.reason)).toBe(true);
    expect(m.reason.length).toBeGreaterThan(0);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("approval_request carries the always-allow proposal", () => {
    const m = fixtures.approval_request_always_allow as ApprovalRequest;
    expect(m.type).toBe("approval_request");
    expect(m.decision_class).toBe("B");
    const proposal = m.proposed_always_allow as PolicyRuleSummary;
    expect(isString(proposal.tool)).toBe(true);
    expect(isString(proposal.args)).toBe(true);
    expect(proposal.effect).toBe("auto");
  });

  it("policy_rules", () => {
    const m = fixtures.policy_rules as PolicyRules;
    expect(m.type).toBe("policy_rules");
    expect(Array.isArray(m.rules)).toBe(true);
    expect(m.rules.length).toBeGreaterThan(0);
    for (const rule of m.rules) {
      expect(isString(rule.tool)).toBe(true);
      expect(isString(rule.args)).toBe(true);
      expect(["auto", "ask", "never"]).toContain(rule.effect);
    }
  });

  it("decision_logged", () => {
    const m = fixtures.decision_logged as DecisionLogged;
    expect(m.type).toBe("decision_logged");
    expect(m.decision_class).toBe("A");
    expect(isString(m.what)).toBe(true);
    expect(isString(m.why)).toBe(true);
    expect(isString(m.commit)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("checkpoint_notice", () => {
    const m = fixtures.checkpoint_notice as CheckpointNotice;
    expect(m.type).toBe("checkpoint_notice");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.code)).toBe(true);
    expect(isString(m.message)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("cost_update", () => {
    const m = fixtures.cost_update as CostUpdate;
    expect(m.type).toBe("cost_update");
    expect(isNumber(m.turn_cost)).toBe(true);
    expect(isNumber(m.session_cost)).toBe(true);
    expect(isNumber(m.total_cost)).toBe(true);
    expect(isNumber(m.classifier_cost)).toBe(true);
    expect(typeof m.cost_by_tier).toBe("object");
    expect(Object.values(m.cost_by_tier).every(isNumber)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("tier_state", () => {
    const m = fixtures.tier_state as TierState;
    expect(m.type).toBe("tier_state");
    expect(["brain", "worker", "validator"]).toContain(m.tier);
    expect(m.override).toBeNull();
    expect(isString(m.model_slugs.brain)).toBe(true);
    const ov = fixtures.tier_state_override as TierState;
    expect(ov.tier).toBe("validator");
    expect(ov.override).toBe("validator");
  });

  it("boundary_update carries the attachment caps (TD-1709)", () => {
    // The composer refuses an oversize file against these, so a drift here
    // means the early refusal disagrees with the daemon's real answer.
    const m = fixtures.boundary_update as BoundaryUpdate;
    expect(m.attachments).toBeDefined();
    expect(isNumber(m.attachments?.max_file_bytes)).toBe(true);
    expect(isNumber(m.attachments?.max_total_bytes)).toBe(true);
    expect(isNumber(m.attachments?.max_count)).toBe(true);
  });

  it("user_message carries attachments when there are any (TD-1709)", () => {
    const plain = fixtures.user_message as UserMessage;
    // The fixture is a Pydantic dump, so the default materialises as `[]`.
    // The client omits the key instead; both parse, which is what makes the
    // field additive rather than a version bump.
    expect(plain.attachments).toEqual([]);

    const withFiles = fixtures.user_message_attachments as UserMessage;
    expect(withFiles.type).toBe("user_message");
    expect(Array.isArray(withFiles.attachments)).toBe(true);
    const first = withFiles.attachments?.[0] as Attachment;
    expect(isString(first.name)).toBe(true);
    // base64, because the daemon decides whether the bytes are text.
    expect(atob(first.content_b64)).toBe("# Title\n");
    // An empty file is legal text and encodes to an empty string.
    expect((withFiles.attachments?.[1] as Attachment).content_b64).toBe("");
  });

  it("boundary_update", () => {
    const m = fixtures.boundary_update as BoundaryUpdate;
    expect(m.type).toBe("boundary_update");
    expect(Array.isArray(m.writable_paths)).toBe(true);
    expect(Array.isArray(m.allowed_commands)).toBe(true);
    expect(isString(m.network) || Array.isArray(m.network)).toBe(true);
    expect(isNumber(m.spend_usd)).toBe(true);
    expect(isNumber(m.wall_clock_hours)).toBe(true);
    expect(isNumber(m.max_iterations)).toBe(true);
    expect(isString(m.source)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("turn_complete", () => {
    const m = fixtures.turn_complete as TurnComplete;
    expect(m.type).toBe("turn_complete");
    expect(isNumber(m.tokens)).toBe(true);
    expect(isNumber(m.cost)).toBe(true);
    expect(m.tier).toBe("worker");
    expect(isNumber(m.duration)).toBe(true);
    expect(isBoolean(m.failed)).toBe(true);
    expect(m.failed).toBe(false);
    expect(m.error_code).toBeNull();
    expect(isNumber(m.seq)).toBe(true);
  });

  it("turn_complete_failed", () => {
    const m = fixtures.turn_complete_failed as TurnComplete;
    expect(m.type).toBe("turn_complete");
    expect(m.failed).toBe(true);
    expect(m.error_code).toBe("auth_failed");
  });

  it("context_compacted", () => {
    const m = fixtures.context_compacted as ContextCompacted;
    expect(m.type).toBe("context_compacted");
    expect(isNumber(m.dropped_messages)).toBe(true);
    expect(isNumber(m.kept_messages)).toBe(true);
    expect(isNumber(m.tokens_before)).toBe(true);
    expect(isNumber(m.tokens_after)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("steering_reloaded", () => {
    const m = fixtures.steering_reloaded as SteeringReloaded;
    expect(m.type).toBe("steering_reloaded");
    expect(isString(m.prefix_hash)).toBe(true);
    expect(isNumber(m.prefix_tokens)).toBe(true);
    expect(isNumber(m.steering_tokens)).toBe(true);
    // The steering figure is the block alone, so it is strictly smaller
    // than the prefix that also carries the base prompt and the root.
    expect(m.steering_tokens).toBeLessThan(m.prefix_tokens);
    expect(isNumber(m.source_count)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("rule_activated", () => {
    const m = fixtures.rule_activated as RuleActivated;
    expect(m.type).toBe("rule_activated");
    expect(isString(m.rule_path)).toBe(true);
    expect(isString(m.session_id)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
  });

  it("tier_switched", () => {
    const m = fixtures.tier_switched as TierSwitched;
    expect(m.type).toBe("tier_switched");
    expect(m.tier).toBe("worker");
    expect(m.previous).toBe("brain");
    expect(isNumber(m.seq)).toBe(true);
  });

  it("setup_state", () => {
    // TD-1101: connection-scoped (no session_id), seq=1 like policy_rules.
    const m = fixtures.setup_state as SetupState;
    expect(m.type).toBe("setup_state");
    expect(isBoolean(m.has_api_key)).toBe(true);
    expect(isBoolean(m.key_required)).toBe(true);
    expect(Array.isArray(m.presets)).toBe(true);
    expect(m.presets.every(isString)).toBe(true);
    expect(isString(m.active_preset)).toBe(true);
    expect(isBoolean(m.skip_all_approvals)).toBe(true);
    expect(m.seq).toBe(1);
    expect("session_id" in m).toBe(false);
  });

  it("conversation_reset", () => {
    const m = fixtures.conversation_reset as ConversationReset;
    expect(m.type).toBe("conversation_reset");
    expect(isNumber(m.user_index)).toBe(true);
    expect(isNumber(m.sibling_index)).toBe(true);
    expect(isNumber(m.sibling_count)).toBe(true);
    expect(isString(m.content)).toBe(true);
  });

  it("api_key_validated", () => {
    const m = fixtures.api_key_validated as ApiKeyValidated;
    expect(m.type).toBe("api_key_validated");
    expect(isBoolean(m.ok)).toBe(true);
    expect(isString(m.detail)).toBe(true);
    expect(m.seq).toBe(1);
    expect("session_id" in m).toBe(false);
  });

  it("diagnostics_report", () => {
    // TD-1104: connection-scoped (no session_id), seq=1 like setup_state.
    const m = fixtures.diagnostics_report as DiagnosticsReport;
    expect(m.type).toBe("diagnostics_report");
    expect(m.seq).toBe(1);
    expect("session_id" in m).toBe(false);
    expect(Array.isArray(m.checks)).toBe(true);
    expect(m.checks.length).toBeGreaterThan(0);
    for (const c of m.checks) {
      expect(isString(c.name)).toBe(true);
      expect(["ok", "fail", "skip"]).toContain(c.status);
      expect(isString(c.detail)).toBe(true);
      // `fix` is present-and-string on fails, absent or null otherwise.
      if (c.status === "fail") expect(typeof c.fix).toBe("string");
    }
  });

  it("usage_report", () => {
    // TD-1706: connection-scoped (no session_id), seq=1 like diagnostics_report.
    const m = fixtures.usage_report as UsageReport;
    expect(m.type).toBe("usage_report");
    expect(m.seq).toBe(1);
    expect("session_id" in m).toBe(false);
    expect(Array.isArray(m.rows)).toBe(true);
    // One row per bucket kind, so all three key shapes are covered.
    expect(new Set(m.rows.map((r) => r.bucket))).toEqual(
      new Set(["session", "day", "week"]),
    );
    for (const r of m.rows) {
      expect(["session", "day", "week"]).toContain(r.bucket);
      expect(isString(r.key)).toBe(true);
      expect(isString(r.tier)).toBe(true);
      expect(isNumber(r.prompt_tokens)).toBe(true);
      expect(isNumber(r.cached_prompt_tokens)).toBe(true);
      expect(isNumber(r.completion_tokens)).toBe(true);
      expect(isNumber(r.cost)).toBe(true);
      // Classifier spend always rides its own field (TD-703).
      expect(isNumber(r.classifier_cost)).toBe(true);
    }
  });

  it("usage_exported", () => {
    const m = fixtures.usage_exported as UsageExported;
    expect(m.type).toBe("usage_exported");
    expect(m.seq).toBe(1);
    expect(["jsonl", "csv"]).toContain(m.format);
    expect(isString(m.path)).toBe(true);
    expect(isNumber(m.rows)).toBe(true);
  });

  it("ping", () => {
    // TD-1716: the liveness frame is the one daemon→client frame with no seq
    // and no session — a fact about the connection, not an event in any log.
    const m = fixtures.ping as Ping;
    expect(m.type).toBe("ping");
    expect("seq" in m).toBe(false);
    expect("session_id" in m).toBe(false);
  });

  it("error", () => {
    const m = fixtures.error as Error;
    expect(m.type).toBe("error");
    expect(isString(m.code)).toBe(true);
    expect(isString(m.message)).toBe(true);
    expect(isNumber(m.seq)).toBe(true);
    // error_with_session has session_id
    const m2 = fixtures.error_with_session as Error;
    expect(isString(m2.session_id)).toBe(true);
  });
});

// ── Structural checks ─────────────────────────────────────────────────

describe("All fixtures have required shape", () => {
  it("every client message has a type field", () => {
    const clientTypes = [
      "hello", "open_workspace", "user_message", "fork_from", "set_branch", "approve", "deny",
      "deny_no_reason", "always_allow", "list_policy_rules", "revoke_policy_rule",
      "set_skip_all_approvals",
      "cancel", "attach", "detach", "set_tier",
      "get_instruction_stack",
      "list_instructions", "create_rule",
      "memory_accept", "memory_edit", "memory_reject", "end_session",
      "get_setup_state", "set_api_key", "validate_api_key", "set_preset",
      "run_diagnostics",
      "get_usage", "export_usage",
    ];
    for (const key of clientTypes) {
      const msg = (fixtures as Record<string, unknown>)[key] as Record<string, unknown>;
      expect(typeof msg.type).toBe("string");
    }
  });

  it("every daemon event has a type and seq field", () => {
    const eventTypes = [
      "ready", "session_state", "conversation_reset", "user_turn", "assistant_delta", "assistant_reasoning", "tool_call", "tool_result",
      "tool_result_truncated", "tool_result_diff", "tool_result_denied",
      "shell_output", "approval_request", "approval_request_always_allow", "decision_logged",
      "checkpoint_notice", "cost_update", "boundary_update", "turn_complete",
      "tier_state", "context_compacted", "steering_reloaded", "rule_activated", "tier_switched",
      "instruction_stack", "instruction_files", "memory_proposal", "session_list", "policy_rules", "error",
      "error_with_session", "setup_state", "api_key_validated",
      "diagnostics_report", "usage_report", "usage_exported",
    ];
    for (const key of eventTypes) {
      const evt = (fixtures as Record<string, unknown>)[key] as Record<string, unknown>;
      expect(typeof evt.type).toBe("string");
      expect(typeof evt.seq).toBe("number");
    }
  });
});

// ── Session lifecycle (TD-1715) ───────────────────────────────────────
//
// Three verbs added to the client union and one field added to every
// session summary. The union and the daemon's known-type set are separate
// lists in protocol.py, and a message in only one of them fails at runtime
// rather than at import — so these fixtures come from the Python side that
// checks both.

describe("Session lifecycle messages match TypeScript types", () => {
  it("archive_session", () => {
    const m = fixtures.archive_session as ArchiveSession;
    expect(m.type).toBe("archive_session");
    expect(isString(m.session_id)).toBe(true);
    expect(m.archived).toBe(true);
  });

  it("archive_session carries the restore direction too", () => {
    const m = fixtures.unarchive_session as ArchiveSession;
    expect(m.type).toBe("archive_session");
    expect(m.archived).toBe(false);
  });

  it("delete_session", () => {
    const m = fixtures.delete_session as DeleteSession;
    expect(m.type).toBe("delete_session");
    expect(isString(m.session_id)).toBe(true);
  });

  it("move_session", () => {
    const m = fixtures.move_session as MoveSession;
    expect(m.type).toBe("move_session");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.workspace_path)).toBe(true);
  });

  it("instruction_files", () => {
    const m = fixtures.instruction_files as InstructionFiles;
    expect(m.type).toBe("instruction_files");
    expect(isString(m.workspace_path)).toBe(true);
    expect(Array.isArray(m.files)).toBe(true);
  });

  it("memory_proposal", () => {
    const m = fixtures.memory_proposal as MemoryProposal;
    expect(m.type).toBe("memory_proposal");
    expect(isString(m.session_id)).toBe(true);
    expect(isString(m.proposal_id)).toBe(true);
    expect(Array.isArray(m.files)).toBe(true);
    expect(m.files[0]?.action).toBe("replace");
  });

  it("every session summary reports whether it is archived", () => {
    const list = fixtures.session_list as SessionList;
    expect(list.sessions.length).toBeGreaterThan(1);
    for (const s of list.sessions as SessionSummary[]) {
      expect(isBoolean(s.archived)).toBe(true);
    }
    expect(list.sessions.some((s) => s.archived)).toBe(true);
    expect(list.sessions.some((s) => !s.archived)).toBe(true);
  });
});
